### ISSUE TITLE
Brief error message when rendering outputs for the first time.

### ISSUE THREAD

**Issue by Data-Jack** [MonkmanMH/Bayesball#3]
Hi, Saw your app on R bloggers looks great! Thought I would mention a way you can lose those error messages that appear for a brief second when you first view a reactive output. In your render functions you should look into the [req() function](https://shiny.rstudio.com/reference/shiny/latest/req.html). Adding this containing the required inputs at the beginning of your render functions means it wont execute unless all the inputs 'exist'. Hope this helps

**Comment by MonkmanMH** [comment]
Thanks ... the req() function is now added, and voila, no temporary error.
